name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]

    name: Test (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          extensions: json, simple-xml

      - name: Install all dependencies
        run: composer install

      - name: Run tests
        run: composer test
